#define LESSON_NAME_MAX 12
#define SCHOOL_DAYS_IN_WEEK 5
#define TEACHER_NAME_MAX 5
#define LESSONS_PER_DAY_MAX 8
#define NUMBER_OF_DIFFERENT_LESSONS 14
#define LESSON_OVER_MIDDAY 3
#define NUMBER_OF_HEAVY_LESSONS 5
#define NUMBER_OF_CLASSES 9
#define TOO_MANY_OF_LESSON -2
#define NUMBER_OF_SUBJECTS 13

#define MAX_LESSONS_IN_ROW 3

#define NUMBER_OF_FREE_REQ 4

#define SIZE_OF_POPULATION 100
#define NUMBER_OF_GENERATIONS 200

#define CHANCE_OF_MUTATION 20
#define MAX_MUTATIONS_PER_INDIVIDUAL 8

#define FITNESS_LESSONS_IN_ROW 80
#define FITNESS_PARALEL_CLASS 100
#define FITNESS_HEAVY_LESSONS -200
#define FITNESS_HEAVY_LESSONS_BEFORE 200
#define FITNESS_FREE_IN_MIDLE -100000
#define FITNESS_MANY_LESSONS_IN_ROW -500
#define FITNESS_TEACHER_OVERBOOKED -2000
#define FITNESS_TEACHER_PREPARATION 60
#define FITNESS_NOT_MEET_REQ -60
#define FITNESS_WAY_OVER_REQ -8000
#define FITNESS_CORRECT_LESSONS 100
#define FITNESS_BONUS_FREE_END 70
#define FITNESS_PERFECTION_BONUS 500
#define FITNESS_NO_FREE_TIME -100
#define FITNESS_NOT_OVERBOOKED 50